language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - ruby-head
  - jruby-1.7.19
before_install: gem update --system && gem install bundler
after_success: bundle exec codeclimate-test-reporter
sudo: false
addons:
  code_climate:
    repo_token: cde93e7ea7084ab026056853a375c08e590bd07541f2c2a51feb4388cf872156
